services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: no
    hostname: scratch-mssql
    environment:
      - ACCEPT_EULA=Y
      # - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_SA_PASSWORD=Tester017!
      - MSSQL_PID=Developer
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backups
      - MSSQL_LCID=1033
      - TZ=Etc/UTC
    ports:
      - 14330:1433
    volumes:
      - mssql-data:/var/opt/mssql
      - mssql-backup:/var/opt/mssql/backups

volumes:
  mssql-data:
  mssql-backup:
